### ISSUE TITLE
excludeClasses is deprecated

### ISSUE THREAD

**Issue by htuscher** [ttreeagency/Scheduler#22]
```yaml
Neos:
  Flow:
    object:
      excludeClasses:
        beberlei.assert:
          - '.*'
        mtdowling.cronexpression:
          - '.*'
```

is deprecated and not longer allowed according to the `Neos.Flow.object.schema.yaml`.

This causes an error in the Neos backend.
